-- Excluindo possíveis tabelas pré existentes para evitar conflitos
DROP TABLE t_alert;

DROP TABLE t_severity;


-- Criando as tabelas necessárias
CREATE TABLE t_severity (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description    VARCHAR2(15) NOT NULL,
    severity_level NUMBER NOT NULL
);

CREATE TABLE t_alert (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR2(55) NOT NULL,
    description VARCHAR2(150) NOT NULL,
    start_time  DATE NOT NULL,
    end_time    DATE,
    station     VARCHAR2(55) NOT NULL,
    id_severity NUMBER NOT NULL,
    FOREIGN KEY ( id_severity ) REFERENCES t_severity ( id )
);


-- Inserindo valores de gravidade (t_severity)
INSERT INTO t_severity ( description, severity_level ) VALUES ( 'Informativo', 1 );

INSERT INTO t_severity ( description, severity_level ) VALUES ( 'Atenção',     2 );

INSERT INTO t_severity ( description, severity_level ) VALUES ( 'Alerta',      3 );

INSERT INTO t_severity ( description, severity_level ) VALUES ( 'Crítico',     4 );

INSERT INTO t_severity ( description, severity_level ) VALUES ( 'Emergência',  5 );


-- Inserindo valores iniciais de alerta (t_alert)
INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Atraso operacional',
         'Trens circulando com velocidade reduzida por conta de manutenção preventiva.',
         TO_DATE('2025-05-07 12:00', 'YYYY-MM-DD HH24:MI'),
         NULL,
         'Luz',
         2 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Falha elétrica',
         'Interrupção parcial na estação por falha na rede aérea.',
         TO_DATE('2025-05-06 17:15', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-06 21:15', 'YYYY-MM-DD HH24:MI'),
         'República',
         3 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Objetos na via',
         'Operação temporariamente interrompida devido a objeto não identificado.',
         TO_DATE('2025-05-06 05:00', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-06 06:00', 'YYYY-MM-DD HH24:MI'),
         'Higienópolis-Mackenzie',
         4 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Pane em trem',
         'Trem apresentou falha e foi recolhido. Intervalo aumentado entre estações.',
         TO_DATE('2025-05-05 18:30', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-05 20:30', 'YYYY-MM-DD HH24:MI'),
         'Paulista',
         3 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Alagamento',
         'Entrada de água nas plataformas. Acesso parcialmente bloqueado.',
         TO_DATE('2025-05-08 22:30', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-09 02:30', 'YYYY-MM-DD HH24:MI'),
         'Fradique Coutinho',
         4 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Atualização de sistema',
         'Sistema de bilhetagem passará por manutenção nesta madrugada.',
         TO_DATE('2025-05-04 02:00', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-04 04:00', 'YYYY-MM-DD HH24:MI'),
         'Faria Lima',
         1 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Obra de acessibilidade',
         'Reforma no elevador pode causar lentidão nos acessos.',
         TO_DATE('2025-05-07 10:15', 'YYYY-MM-DD HH24:MI'),
         NULL,
         'Pinheiros',
         2 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Furto de cabos',
         'Circulação comprometida devido a furto de cabos.',
         TO_DATE('2025-05-06 06:00', 'YYYY-MM-DD HH24:MI'),
         NULL,
         'Butantã',
         4 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Teste de alarme',
         'Teste sonoro programado. Sem impacto na operação.',
         TO_DATE('2025-05-08 11:45', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-08 13:45', 'YYYY-MM-DD HH24:MI'),
         'São Paulo-Morumbi',
         1 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Aviso de segurança',
         'Volume elevado de passageiros em horário de pico. Tenha atenção nos acessos.',
         TO_DATE('2025-05-06 17:30', 'YYYY-MM-DD HH24:MI'),
         NULL,
         'Vila Sônia',
         2 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Limpeza especial',
         'Limpeza pesada programada após fechamento.',
         TO_DATE('2025-05-04 23:00', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-05 01:00', 'YYYY-MM-DD HH24:MI'),
         'Luz',
         1 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Vazamento de água',
         'Vazamento identificado em banheiro. Equipe já acionada.',
         TO_DATE('2025-05-07 08:15', 'YYYY-MM-DD HH24:MI'),
         NULL,
         'República',
         2 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Usuário na via',
         'Interrupção após presença de pessoa nos trilhos.',
         TO_DATE('2025-05-06 07:45', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-06 08:45', 'YYYY-MM-DD HH24:MI'),
         'Higienópolis-Mackenzie',
         3 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Ocorrência policial',
         'Investigação em andamento. Trens circulando normalmente.',
         TO_DATE('2025-05-05 19:00', 'YYYY-MM-DD HH24:MI'),
         NULL,
         'Paulista',
         2 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Bloqueio de acesso',
         'Escada rolante interditada para manutenção.',
         TO_DATE('2025-05-08 14:30', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-08 18:30', 'YYYY-MM-DD HH24:MI'),
         'Fradique Coutinho',
         2 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Pane no sistema de som',
         'Sistema de áudio temporariamente indisponível.',
         TO_DATE('2025-05-06 15:00', 'YYYY-MM-DD HH24:MI'),
         NULL,
         'Faria Lima',
         1 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Queda de energia',
         'Pane elétrica geral afeta serviços na estação.',
         TO_DATE('2025-05-05 03:15', 'YYYY-MM-DD HH24:MI'),
         NULL,
         'Pinheiros',
         5 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Animais na via',
         'Presença de animal avistado nos trilhos.',
         TO_DATE('2025-05-06 06:45', 'YYYY-MM-DD HH24:MI'),
         NULL,
         'Butantã',
         3 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Revisão técnica emergencial',
         'Verificação urgente no sistema de freios.',
         TO_DATE('2025-05-07 20:00', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-07 22:30', 'YYYY-MM-DD HH24:MI'),
         'São Paulo-Morumbi',
         4 );

INSERT INTO t_alert ( title, description, start_time, end_time, station, id_severity )
VALUES ( 'Manutenção preventiva',
         'Equipe atuando na plataforma. Operação normal.',
         TO_DATE('2025-05-06 13:15', 'YYYY-MM-DD HH24:MI'),
         TO_DATE('2025-05-06 17:15', 'YYYY-MM-DD HH24:MI'),
         'Vila Sônia',
         1 );


COMMIT;